Added environment handling and JSON string creation for logging
Queueing-Systems-Assistance/qsa-formula-handler pull request #26
Opened 2020-10-17 08:16 UTC by kcsanad98

2020-10-17 09:09 UTC, ZoltanSzilagyiCse approved these changes

2020-10-17 10:44 UTC, ZoltanSzilagyiCse requested changes

2020-10-17 10:44 UTC, ZoltanSzilagyiCse commented on src/logger/qsa-logger.service.ts
> +const PROD_INSTANCE = 'formula-handler-prod'
Because we'll set the value from the docker, I'd remove this variable and use only one: `APP_INSTANCE = 'formula-handler-local'` and in the docker, we can set the value to `-e APP_INSTANCE=formula-handler-prod` or if we use it in the lab, then set to the lab. Right now, we set these values based on the environment, and we keep both prod and lab value in a hardcoded string which is not recommended.

2020-10-17 14:34 UTC, kcsanad98 commented on src/logger/qsa-logger.service.ts
> +const PROD_INSTANCE = 'formula-handler-prod'
It's set based on the environment variable called ENVIRONMENT.
```
instance: process.env.ENVIRONMENT == PROD_ENVIRONMENT ? PROD_INSTANCE : LAB_INSTANCE
```
I just thought that using these strings is more expressive.

2020-10-18 19:16 UTC, ZoltanSzilagyiCse approved these changes

2020-10-18 19:16 UTC, ZoltanSzilagyiCse commented on src/logger/qsa-logger.service.ts
> +const PROD_INSTANCE = 'formula-handler-prod'
Discussed :)

2020-10-18 19:31 UTC, merged